#
# ### Continueous Integration (CI)
#
# Ensure that code successfully builds and deploy for testing
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/vars-all.yaml
- template: vars/vars-ci.yaml

steps:
- template: steps/git-checkout.yaml
- template: steps/build.yaml
- template: steps/docker-build-push.yaml
